disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - multiple_closures_with_trailing_closure

identifier_name:
  excluded: # excluded via string array
    - id
    - ok
    - URL
    - x
    - y
